import crypto from "crypto";

// ! FUNCTION TO HASH AN OTP (ONE-TIME PASSWORD) USING THE SHA-256 ALGORITHM FROM THE CRYPTO MODULE. THIS FUNCTION TAKES AN OTP AS INPUT, CREATES A SHA-256 HASH OF IT, AND RETURNS THE HASH IN HEXADECIMAL FORMAT. HASHING THE OTP BEFORE STORING IT IN THE DATABASE ENHANCES SECURITY BY ENSURING THAT THE ACTUAL OTP VALUE IS NOT STORED IN PLAIN TEXT, MAKING IT MORE DIFFICULT FOR ATTACKERS TO RETRIEVE THE ORIGINAL OTP EVEN IF THEY GAIN ACCESS TO THE DATABASE.

const hashOtp = otp => {
  return crypto.createHash("sha256").update(otp).digest("hex");
};

export default hashOtp;