export const ACTIVITY_TYPES = {
  //  ORGANIZATION ACTIVITIES
  ORGANIZATION_CREATED: "ORGANIZATION_CREATED",
  MEMBER_ADDED: "MEMBER_ADDED",
  MEMBER_REMOVED: "MEMBER_REMOVED",
  MEMBER_ROLE_UPDATED: "MEMBER_ROLE_UPDATED",
  OWNERSHIP_TRANSFERRED: "OWNERSHIP_TRANSFERRED",
  MEMBER_LEFT: "MEMBER_LEFT",

  // PROJECT ACTIVITIES
  PROJECT_CREATED: "PROJECT_CREATED",
  PROJECT_UPDATED: "PROJECT_UPDATED",
  PROJECT_MEMBER_ADDED: "PROJECT_MEMBER_ADDED",
  PROJECT_MEMBER_REMOVED: "PROJECT_MEMBER_REMOVED",

  // TASK ACTIVITIES
  TASK_CREATED: "TASK_CREATED",
  TASK_UPDATED: "TASK_UPDATED",
  TASK_ASSIGNED: "TASK_ASSIGNED",
  TASK_STATUS_CHANGED: "TASK_STATUS_CHANGED",
  TASK_COMPLETED: "TASK_COMPLETED",

  // COMMENT AND FILE ACTIVITIES
  COMMENT_ADDED: "COMMENT_ADDED",
  FILE_UPLOADED: "FILE_UPLOADED",
};
