import ms from "ms";
import { JWT_REFRESH_TOKEN_EXPIRATION, NODE_ENV } from "../config/env.js";

// ! FUNCTION TO SET A REFRESH TOKEN IN AN HTTP-ONLY COOKIE WITH APPROPRIATE SECURITY OPTIONS. THIS FUNCTION TAKES THE RESPONSE OBJECT AND THE REFRESH TOKEN AS INPUT, AND SETS A COOKIE NAMED "refreshToken" WITH THE TOKEN VALUE. THE COOKIE IS CONFIGURED TO BE HTTP-ONLY TO PREVENT ACCESS FROM CLIENT-SIDE SCRIPTS, SECURE TO ENSURE IT IS ONLY SENT OVER HTTPS IN PRODUCTION ENVIRONMENTS, SAME-SITE STRICT TO MITIGATE CSRF ATTACKS, AND HAS A MAX AGE SET BASED ON THE JWT_REFRESH_TOKEN_EXPIRATION CONFIGURATION VALUE, WHICH DEFINES HOW LONG THE REFRESH TOKEN SHOULD BE VALID.
const setRefreshTokenCookie = (res, token) => {
  res.cookie("refreshToken", token, {
    httpOnly: true,
    secure: NODE_ENV === "production",
    sameSite: "strict",
    maxAge: ms(JWT_REFRESH_TOKEN_EXPIRATION),
  });
};

export default setRefreshTokenCookie;
