import { NODE_ENV, DEVICE_COOKIE_MAX_AGE } from "../config/env.js";

// ! FUNCTION TO SET A DEVICE ID IN AN HTTP-ONLY COOKIE WITH APPROPRIATE SECURITY OPTIONS. THIS FUNCTION TAKES THE RESPONSE OBJECT AND THE DEVICE ID AS INPUT, AND SETS A COOKIE NAMED "deviceId" WITH THE DEVICE ID VALUE. THE COOKIE IS CONFIGURED TO BE HTTP-ONLY TO PREVENT ACCESS FROM CLIENT-SIDE SCRIPTS, SECURE TO ENSURE IT IS ONLY SENT OVER HTTPS IN PRODUCTION ENVIRONMENTS, SAME-SITE STRICT TO MITIGATE CSRF ATTACKS, AND HAS A MAX AGE SET BASED ON THE DEVICE_COOKIE_MAX_AGE CONFIGURATION VALUE, WHICH DEFINES HOW LONG THE DEVICE ID SHOULD BE STORED IN THE COOKIE. THIS FUNCTION CAN BE USED TO TRACK DEVICES THAT ACCESS USER ACCOUNTS OR IMPLEMENT DEVICE-BASED AUTHENTICATION MECHANISMS, ENHANCING THE SECURITY OF THE APPLICATION BY ALLOWING IT TO RECOGNIZE AND MANAGE DEVICES ASSOCIATED WITH USER ACCOUNTS.

export const setDeviceCookie = (res, deviceId) => {
  res.cookie("deviceId", deviceId, {
    httpOnly: true,
    secure: NODE_ENV === "production",
    sameSite: "strict",
    maxAge: DEVICE_COOKIE_MAX_AGE,
  });
};
