import crypto from "crypto";

// ! FUNCTION TO GENERATE A UNIQUE DEVICE ID USING THE CRYPTO MODULE'S randomUUID FUNCTION. THIS FUNCTION RETURNS A UNIVERSALLY UNIQUE IDENTIFIER (UUID) IN STRING FORMAT, WHICH CAN BE USED TO UNIQUELY IDENTIFY A DEVICE IN THE APPLICATION. THIS IS USEFUL FOR SECURITY PURPOSES, SUCH AS TRACKING DEVICES THAT ACCESS USER ACCOUNTS OR IMPLEMENTING DEVICE-BASED AUTHENTICATION MECHANISMS.
export const generateDeviceId = () => {
  return crypto.randomUUID();
};