import ms from "ms";
import { JWT_REFRESH_TOKEN_EXPIRATION } from "../config/env.js";

// ! FUNCTION TO CALCULATE THE EXPIRATION DATE FOR A REFRESH TOKEN BASED ON THE CURRENT TIME AND THE JWT_REFRESH_TOKEN_EXPIRATION CONFIGURATION VALUE. THIS FUNCTION RETURNS A DATE OBJECT REPRESENTING THE EXACT TIME WHEN THE REFRESH TOKEN SHOULD EXPIRE, IS USED TO SET THE EXPIRATION TIME IN THE DATABASE AFTER A CERTAIN PERIOD. THIS HELPS ENSURE THAT REFRESH TOKENS ARE INVALIDATED AFTER A CERTAIN PERIOD, ENHANCING THE SECURITY OF THE AUTHENTICATION SYSTEM BY LIMITING THE WINDOW OF OPPORTUNITY FOR TOKEN ABUSE.

// ? ms IS A UTILITY FUNCTION THAT CONVERTS THE JWT_REFRESH_TOKEN_EXPIRATION VALUE (WHICH IS A STRING REPRESENTING A DURATION, SUCH AS "7d" FOR 7 DAYS) INTO MILLISECONDS, AND THEN WE ADD THIS DURATION TO THE CURRENT TIME (Date.now()) TO GET THE FUTURE EXPIRATION TIME FOR THE REFRESH TOKEN.

const getRefreshTokenExpiry = () => {
  return new Date(Date.now() + ms(JWT_REFRESH_TOKEN_EXPIRATION));
};

export default getRefreshTokenExpiry;
