import crypto from "crypto";

// ! FUNCTION TO GENERATE A FINGERPRINT FOR A DEVICE BASED ON THE DEVICE ID AND USER AGENT STRING. THIS FUNCTION COMBINES THE DEVICE ID AND USER AGENT INTO A SINGLE STRING, THEN USES THE SHA-256 HASHING ALGORITHM FROM THE CRYPTO MODULE TO CREATE A UNIQUE FINGERPRINT. THIS FINGERPRINT CAN BE USED TO IDENTIFY DEVICES IN THE APPLICATION, ENHANCING SECURITY BY ALLOWING THE SYSTEM  TO RECOGNIZE AND MANAGE DEVICES ASSOCIATED WITH USER ACCOUNTS, AND TO DETECT POTENTIAL FRAUDULENT ACTIVITY BY IDENTIFYING UNRECOGNIZED DEVICES.

export const generateFingerprint = (deviceId, userAgent) => {
  const rawFingerprint = `${deviceId}:${userAgent}`;
  return crypto.createHash("sha256").update(rawFingerprint).digest("hex");
};
